name: build

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2

  - name: Check clang-format conformity
    run: bash .github/clang-lint.sh

#    - name: Build on Arduino CLI
#      run: bash ci/build-arduino.sh
