name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check clang-format conformity
      run: bash .github/clang-lint.sh

    - name: Build tests
      # Build / Execute tests defined in tests folder
      working-directory: ${{ github.workspace }}/tests
      run: make

#    - name: Build on Arduino CLI
#      run: bash ci/build-arduino.sh
